### ISSUE TITLE
File not found error on Heroku

### ISSUE THREAD

**Issue by iAnanich** [Shokesu/splash#1]
Locally container works great, but on Heroku server it throws an error:
```
app[web.1]: [-] Log opened.
app[web.1]: [-] Splash version: 3.0
app[web.1]: [-] Qt 5.9.1, PyQt 5.9, WebKit 602.1, sip 4.19.3, Twisted 16.1.1, Lua 5.2
app[web.1]: [-] Python 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
app[web.1]: [-] Open files limit: 10000
app[web.1]: [-] Can't bump open files limit
app[web.1]: [-] Xvfb is started: ['Xvfb', ':1628323967', '-screen', '0', '1024x768x24', '-nolisten', 'tcp']
app[web.1]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-u40613'
app[web.1]: [-] Traceback (most recent call last):
app[web.1]: [-]   File "/app/bin/splash", line 4, in <module>
app[web.1]: [-]     main()
app[web.1]: [-]   File "/app/splash/server.py", line 388, in main
app[web.1]: [-]     server_factory=server_factory,
app[web.1]: [-]   File "/app/splash/server.py", line 283, in default_splash_server
app[web.1]: [-]     allowed_schemes=allowed_schemes,
app[web.1]: [-]   File "/app/splash/network_manager.py", line 57, in __init__
app[web.1]: [-]     self.adblock_rules = AdblockRulesRegistry(filters_path, verbosity=verbosity)
app[web.1]: [-]   File "/app/splash/request_middleware.py", line 159, in __init__
app[web.1]: [-]     self._load(path)
app[web.1]: [-]   File "/app/splash/request_middleware.py", line 183, in _load
app[web.1]: [-]     for fname in os.listdir(path):
app[web.1]: [-] FileNotFoundError: [Errno 2] No such file or directory: '/etc/splash/filters'
```
**note** data about date was removed from the log entries above.

**Comment by iAnanich** [comment]
I fund out that when starting it locally, 8th log-entry looks like 
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
```
 the difference is between default values:
`/tmp/runtime-root` <-> `/tmp/runtime-u40613`

**Comment by andresvidal** [comment]
So what's the fix?

**Comment by iAnanich** [comment]
As remember, there is no fix - it just won't work on Heroku because of how Heroku manages file system.
